[package]
name = "agent-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = {version="0.12.12", features=["json"]}
rodio = "0.20.1"
serde = {version="1.0.217", features=["derive"]}
serde_json = "1.0.135"
tokio = {version = "1.43.0", features = ["full"]}
